[2024-08-01 00:51:10,733] 	INFO 	27 	emissions_data.py 	<module>() 	Emissions Data Started
[2024-08-01 00:52:44,778] 	INFO 	99 	emissions_data.py 	<module>() 	Emissions Data Ended
[2024-08-01 01:04:01,144] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 01:09:37,942] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 01:09:38,642] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 01:09:40,044] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 01:09:40,044] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 01:09:42,436] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 01:09:42,436] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 01:09:45,145] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 01:09:45,971] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 01:11:16,047] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 01:11:16,047] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 01:11:16,191] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,512] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,649] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,787] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:16,949] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:17,828] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:18,138] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:18,735] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:19,651] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:20,440] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:23,444] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:23,575] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,160] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,451] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:24,800] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:25,448] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:26,617] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:27,130] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:28,376] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:29,126] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:11:33,494] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 01:12:02,505] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 01:12:02,506] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 01:12:39,106] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 01:12:39,986] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 01:45:10,955] 	ERROR 	156 	bribe_data.py 	<module>() 	Error occurred during Bribe Data process. Error: Dataframe is empty
[2024-08-01 01:45:11,581] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 01:45:27,513] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 01:45:28,099] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 01:45:39,635] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 01:45:40,224] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 01:47:54,716] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 01:47:54,716] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 01:48:42,144] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 01:48:42,144] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 01:48:54,169] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-01 06:18:22,484] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 06:22:24,905] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 06:22:25,522] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 06:22:27,590] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 06:22:27,590] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 06:22:29,636] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 06:22:29,636] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 06:22:32,378] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 06:22:33,142] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 06:23:43,572] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 06:23:43,572] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 06:23:43,857] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,298] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,522] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,729] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:44,914] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:46,245] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:46,730] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:47,593] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:49,117] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:50,324] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:54,796] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:55,004] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:55,953] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:56,376] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:56,856] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:57,896] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:59,376] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:23:59,994] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:01,917] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:02,989] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:09,237] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 06:24:18,530] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 06:24:18,530] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 06:24:50,536] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 06:24:51,343] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 07:03:05,566] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-01 07:03:06,145] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 07:03:35,820] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 07:03:36,393] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 07:03:48,555] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 07:03:49,091] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 07:04:40,712] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: jBRL/BRZ, Address: 0xa0695f78af837f570bcc50f53e58cda300798b65, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:40,867] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: XCAD(old)/USDT, Address: 0x46c69a989dc56747f007acfa4d6bc7c9fa8137bf, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,033] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/PLAY, Address: 0xb8a85b80a12931fe2a1f5db9295fbdae03616e9b, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,200] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: MPX/BNB, Address: 0x51bfc6e47c96d2b8c564b0ddd2c44fc03707cdc7, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,367] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: sfrxETH/FXS, Address: 0x425198ea58ab9cf9001f59c8aeb8c413a6dbe1b1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,515] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: MIX/BNB, Address: 0x0f7d50a2728de6f94b3ac8013031f527572cc9f1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,675] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: PSTAKE/BUSD, Address: 0x67e51f1de32318f3a27265287ed766839a62cf13, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,824] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ankrBNB/BNB, Address: 0x9c9ead6cfd1ed4dd17cd44eb12229364dd541697, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:41,979] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: lisUSD/USDT, Address: 0x6ce8014488877f91234ef23012193de6bb0009a8, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,128] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ankrBNB/THE, Address: 0x3575155f5b0eada1e4fda5bc84e2c2c7cef1d9f2, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,284] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: jBRL/BNB, Address: 0xf019759f450c8a1c8cfd4e9ecd34e09f72d7fae5, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,472] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDT/ERN, Address: 0x3666f5900e50870e2f84b9a7a26a1ec68adea8bb, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,626] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: CSIX/USDT, Address: 0xce7c38ece02b55070208b2e070585ea5321748e1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,784] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ankrBNB/BNB, Address: 0xfa0429a7eab25ec8d31e247e725afd931cf6bdfe, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:42,932] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: NGL/USDT, Address: 0xd949476184b9c94ed2130e8175d4139654ce2339, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:04:43,096] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BETS/BNB, Address: 0x21f60af65ba9a20c3320b6938aaa60237f6beea8, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 07:05:20,342] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 07:05:20,342] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 07:06:27,042] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 07:06:27,042] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 07:06:48,014] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-01 12:24:41,770] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 12:28:55,080] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 12:28:55,899] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 12:28:57,772] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 12:28:57,772] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 12:28:59,206] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 12:28:59,206] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 12:29:01,919] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 12:29:02,837] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 12:30:19,761] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 12:30:19,761] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 12:30:19,870] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,093] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,241] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,348] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:20,474] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:21,282] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:21,546] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:22,037] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:22,616] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:23,199] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:25,628] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:25,767] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:26,232] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:26,458] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:26,695] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:28,091] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:28,419] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:29,419] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:29,998] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:33,559] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 12:30:39,764] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 12:30:39,764] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 12:31:12,931] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 12:31:13,885] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 12:55:43,695] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-01 12:55:44,388] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 12:56:03,488] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 12:56:04,153] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 12:56:14,004] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 12:56:14,669] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 12:58:18,118] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 12:58:18,118] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 12:58:53,608] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 12:58:53,608] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 12:59:14,413] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-01 18:16:51,007] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-01 18:20:21,544] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-01 18:20:22,211] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-01 18:20:24,010] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-01 18:20:24,010] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-01 18:20:26,236] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-01 18:20:26,237] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-01 18:20:29,192] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-01 18:20:30,047] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-01 18:21:23,936] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/ankrBNB, Address: 0xC6dB38F34DA75393E9aac841c08104348997D509, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,104] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/WBNB, Address: 0xc7419EBbc4b259C50D7Eeaba49940688A5d52Afa, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,271] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/MIX, Address: 0xC8c8148Fc304503941DfFFe0b28211472597aB74, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,429] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/DEUS, Address: 0xC8Da40f8A354530F04CE2dDe98Ebc2960a9eA449, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,591] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XRP/WBNB, Address: 0xC9688a1e9dBE45F253CC77cB9726A11b323bFD54, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,748] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FITFI/BUSD, Address: 0xcAe2C0d6937671490D3bcE4C21d57fF313f407Eb, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:24,932] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-fBOMB/WBNB, Address: 0xCcDEdaC1973b6d2542fB1b7EcE843b81A9ee7070, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,087] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CSIX/USDT, Address: 0xCE7C38ECe02b55070208b2e070585eA5321748e1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,251] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-qTHE/THE, Address: 0xCEd2490a69aeD204e7A10e4Aa10DdDce5224287D, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,417] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/LIQ, Address: 0xD27F175c12C9d147ff1be4844856F224fD6223C4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,573] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/WBNB, Address: 0xD328D129E46f9B978416599913102e8CD64593F3, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,734] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/sFRAX, Address: 0xD46Da49357a3c9da115b3bf20B31b2cf3e5dE58B, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:25,893] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/FITFI, Address: 0xD523AC2609c3A56f945242CC239e9F47c018bf6b, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,049] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/BUSD, Address: 0xD5B7877cD8056f38bB37FaDb63FE698E406F3870, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,216] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/FXS, Address: 0xd6C883ABA697b33110e42077D28361aa3E48f26A, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,391] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-UNW/THE, Address: 0xd714206a7D63F5a2d613064815995E9CC7061988, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,557] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-NGL/USDT, Address: 0xD949476184B9c94Ed2130E8175D4139654CE2339, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,726] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/USDC, Address: 0xD9937a059D2FCAb6cB0C11Da71cc91F7b33A3870, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:26,932] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BNBx/ETH, Address: 0xd9BC6271abBE5dd01731B1b9aC2C1Cb0ea5Be246, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,089] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/BTCB OLD, Address: 0xd9F7096625B65Ac37c09d05c1c4548edfcCe9fBE, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,262] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FITFI/WBNB, Address: 0xd9f88F54a73B37463fb8F15ece98e0D1DcdCAAB6, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,420] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/THE, Address: 0xDA2E32203EEe658e0E9b9E1b766ac1ceDb88d1f1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,576] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/RDNT, Address: 0xda57e73e5A2fA00C5c6B660454c1950DCB03E958, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,734] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/dXCAD, Address: 0xDA5edbE3f254046cD8CABeC6758E0B1122B52D6e, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:27,901] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/THE, Address: 0xdAaC487bB3a411cB9251794bb7c7B04cb6d1aB26, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,065] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/BUSD, Address: 0xDC17b8899D8084E64913BD508bb13BfC2696dEBB, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,217] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-PION/WBNB, Address: 0xDC1e387fC2697F3737EE197712BfeF9e1101ccd5, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,381] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DEI/BUSD, Address: 0xDC2b0436E63bD8654aEA52d1aCD3Ae4F9716A6F4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,527] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/THE, Address: 0xdC81698F98e275785741F96961f246368FDd5866, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,684] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DUSD/WBNB, Address: 0xdd0118F593c91ef5FA40C34d5687654C215C3D98, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:28,843] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETS Alpha/BUSD, Address: 0xde34Df68795f0D2b07F64285Ba83601889A6995C, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,003] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MULTI/BUSD, Address: 0xdE4Cc4446205d1138EcAa48B2CB22b8e06E69BD4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,175] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/PRIMAL, Address: 0xde72DD50Dd0ca9C8c48b04F74c5246B5545969D0, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,333] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/LIQ, Address: 0xdf26702B1A510bc6860b2a1DF11219f216b91445, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,491] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CHAM/BUSD, Address: 0xDf63A43aEFb5c1Aa4040a3a121d2a8C00EeBE7d8, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,653] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DAI/MAI, Address: 0xe03e9EcC7d4C45c6985bfB909D9Bb3ACa5Ef18c0, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,819] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/BUSD OLD, Address: 0xe200B5B3F08d1254d05d8797FFA1f99730C0025c, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:29,982] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/multiBTC, Address: 0xE2256f71F3Df4765A3602db66747eA87a71057b5, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:30,135] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/XCAD OLD, Address: 0xe2d25A87e97a1016c35F736Ea77A4d6Bd1919E74, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-01 18:21:44,397] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-01 18:21:44,397] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-01 18:21:44,617] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,026] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,243] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,445] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:45,656] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:46,874] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:47,304] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:48,114] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:49,213] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:50,275] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:54,366] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:54,578] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:55,386] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:55,779] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:56,168] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:58,414] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:21:58,991] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:00,611] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:01,672] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:07,441] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-01 18:22:14,243] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-01 18:22:14,243] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-01 18:22:42,809] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-01 18:22:43,680] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-01 18:58:48,633] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-01 18:58:49,320] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-01 18:59:01,228] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-01 18:59:01,864] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-01 18:59:11,869] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-01 18:59:12,499] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-01 19:01:55,523] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-01 19:01:55,523] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-01 19:03:08,968] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-01 19:03:08,968] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-01 19:03:29,240] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-02 00:58:44,893] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-02 00:59:45,940] 	ERROR 	122 	id_data_v2.py 	<module>() 	Error occurred during ID Data process. Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 00:59:46,654] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-02 01:00:46,926] 	ERROR 	74 	day_data.py 	<module>() 	Error occurred during Day Data process. Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:00:46,926] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-02 01:00:49,107] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-02 01:00:49,107] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-02 01:00:52,470] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-02 01:00:53,291] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-02 01:00:59,192] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-OVN/USDT+, Address: 0x0571e491cBfa2FDb449a329196e01E4fDC9cAF7A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:04,209] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DEI/BUSD, Address: 0x06589AbD54582783142E3D1165722e7e10483De0, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:09,226] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-eTHENA/WBNB, Address: 0x06834e10d27f9786F29e382df7f477a4E1589504, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:14,243] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MULTI/WBNB, Address: 0x075E794F631eE81df1aadB510aC6Ec8803B0FA35, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:19,431] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/PENDLE, Address: 0x094B905Cca7B4Afe244B1cB85361d463A280aAF5, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:25,236] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-qTHE/THE, Address: 0x0d075Baccb0614EE93Ebe761A9803D7Ded662ffA, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:30,255] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-frxETH/FRAX, Address: 0x0D8401cBc650e82D1F21A7461efC6409Ef55C4Db, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:35,269] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DOLA/FRAX, Address: 0x0D9aB02ae2110170B8e83B3ABa4E3aC2398Ab541, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:40,290] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-MULTI/WBNB, Address: 0x0dB08Af3BfEE2083C702b20c89Cbcadad68eB51a, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:45,305] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/CHAM, Address: 0x0ec098Aa4bC6A31e4f804E653F0488Eb0FEb1a2A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:50,322] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BUSD/CUSD, Address: 0x0F68c7cCb6a87fe988109A42A446786ddf368eD8, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:50,925] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MAI/FXS, Address: 0x10F9f7355Fb75C73718Afad8AdBc7BF72c5A0715, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:01:51,228] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-PNP/WBNB, Address: 0x11371C79dee1471578F74eb09511AE24E2aa1Cd9, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:01:56,584] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CGPT/BUSD, Address: 0x135Df9Df6e7bBa507BA0DaC6C0469fFF4aF7F864, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:01:56,780] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/SLM, Address: 0x13660309E0001884d53e86Ea21f1EB1D6E330A05, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:01:56,961] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ankrMATIC/MATIC, Address: 0x138104C01d0c8fBEB5D6caA99a38A93E9a7868eB, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:02:01,976] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDC/WBNB, Address: 0x141f1e4022a5ED1d240dd33dCd2b602873eb4EE2, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:06,991] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USD+/CUSD, Address: 0x150990B9630fFe2322999e86905536E2E7e8d93f, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:12,275] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT+/USD+, Address: 0x1561D9618dB2Dcfe954f5D51f4381fa99C8E5689, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:17,296] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/PLAY, Address: 0x16184EC3a17285B33c22B6252c2D94Ca54D03341, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:22,314] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/USDC, Address: 0x16348c6e93ac30604555D7fe74347C606E5d520A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:22,575] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ID/WBNB, Address: 0x1663786974fecF742BdEA32222C96BaE58d0Fc65, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:02:23,193] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-fBOMB/THE, Address: 0x18c12680ACA1A2660ADC88751b49bd156f435b3D, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:02:23,372] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-jEUR/WBNB, Address: 0x18d6583a0238C141EbEB3bA3e39ba4481312ed37, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:02:28,387] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BNBx/USDT, Address: 0x19420fa1D0E350b5d46a8D3B24Ff2421744eB54E, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:33,615] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-sfrxETH/frxETH, Address: 0x1964f694B722045D8cF757e19c9439E38810b5DB, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:38,631] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/XCAD, Address: 0x1a839f1887A76cfC113a494DF08d3b4343aFCE19, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:43,648] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/LINK, Address: 0x1Abd186f1bA4cF6CFF32514454Da180C05e6Df21, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:48,839] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/WBNB, Address: 0x1d168C5b5DEa1c6dA0E9FD9bf4B7607e4e9D8EeC, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:54,037] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/THE, Address: 0x1D6c1De20424831FD6F843f1d39Bf96265B3899D, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:02:59,050] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-BUSD/THE, Address: 0x1DE8Ee98012Dae7861e76ff38Df9DdAC32CCc947, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:04,061] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/BTCB, Address: 0x1EbDf6E38AE6461Ef5C8e97346A02934BA6FAD84, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:09,263] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/FRAX, Address: 0x1Ee0e38a1f6a662f4696F53140E45a00637D3423, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:09,464] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FS/USDT, Address: 0x1F02F41906b4E1909166e542EDA61AB2924c5a37, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:03:14,480] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FIL/WBNB, Address: 0x1f06C7E323Bc3A5C94Bb6B760C128830cDF6ADfB, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:20,045] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BETS/WBNB, Address: 0x21f60Af65Ba9A20c3320B6938aaa60237f6bEEA8, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:20,502] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-dXCAD/BUSD, Address: 0x238a45C2c6531356aE60DA6123340DD203D5336A, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:03:25,518] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-BTCB/multiBTC, Address: 0x2475FF2A7C81da27eA2e08e0d3B0Ad01e16225eC, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:30,535] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/USDC, Address: 0x262029C946D868CA5C339D4eA605e65928e2013A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:35,552] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-cpTHENA/THE, Address: 0x26C8db7549df14e0A922e76f0dc3CC4BAb89cE36, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:40,571] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DOLA/WBNB, Address: 0x271bF92185D0Dc68EC700010789791d303f6A558, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:45,587] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/BUSD, Address: 0x2896b0d3fB19B79fCB7b7EDe832deB6c1621664c, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:50,659] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-PION/WBNB, Address: 0x28E5FC8bCf5e569BfCFF31cdb2ED909782015b80, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:03:51,014] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-stkBNB/THE, Address: 0x2AFED1cA1bC414e123b1C4e30E8F6FC513C8Ee72, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:03:51,543] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/XCAD, Address: 0x2bEb5FEE7f4d58e8e0efEFdFf5161f6E9127a502, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:03:56,558] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DUSD/FRAX, Address: 0x2c3EeC9D939197CaBa5dd2A8271F7665a976A987, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:02,038] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/WBNB, Address: 0x307936b725272Ec6Eb19d4d539207554f31E6231, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:07,055] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BNBx/FRAX, Address: 0x314d95096e49fDe9ebb68aD7E162b6eDd8D4352A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:12,072] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-OATH/LQDR, Address: 0x32629Ff547F1E619f4c37A84fD66624cA0ab01d8, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:17,417] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/CUSD, Address: 0x338cA7eD1D6BeDe03799a36a6f90E107d24Dc6aD, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:22,592] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/SEC, Address: 0x34915f659f820Bee9247956CaB4277A632cFA230, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:27,608] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BUSD/THE, Address: 0x34B897289fcCb43c048b2Cea6405e840a129E021, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:33,088] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/ERN, Address: 0x3666f5900E50870e2F84B9a7A26a1ec68ADEa8bB, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:38,106] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-SnBNB/WBNB, Address: 0x36C78cb2d423451A78FA0f71Fd33d45fd63d8B67, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:43,401] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DOGE/WBNB, Address: 0x37487428A2Cff3E21F9d9452b4F6759cc23e4805, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:48,419] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-liveThe/THE, Address: 0x3765476BfFE43Cf4c0656bF3A7529c54ae247056, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:53,624] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-MORE/arcUSD, Address: 0x3Bfc63Eb779811F59d41045394F612da3F450678, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:04:58,642] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDV/USDT, Address: 0x3BFDA059746caE954925782842b8673901a6D381, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:03,656] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-IDIA/BUSD, Address: 0x3c552e8aC4473222e3d794ADecFA432Eace85929, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:08,672] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/FRAX, Address: 0x3c5e16A6fF3bb4279B520D208C86338f3a404608, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:13,687] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FRAX/FXS, Address: 0x3c9BD1f914D6F0e0CD27a1F77e120c061D1FDbEd, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:18,706] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FEAR/THE, Address: 0x3CE33Ef9F2971b4877d39718dbFEE7C01AC0CAB6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:23,722] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FFH/WBNB, Address: 0x3d3F41D3Faaa4F3e91F9dc65A2790F809e045bB7, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:28,737] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/WBNB OLD, Address: 0x3Ec80A1f547ee6FD5D7FC0DC0C1525Ff343D087C, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:33,752] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDV/WBNB, Address: 0x3F3b8921402c35979FeCC0fF630358615eE38937, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:33,947] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/dXCAD OLD, Address: 0x3f4d5c667D918DcE84c89cC63998776d21081089, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:05:38,961] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ETH/pxETH, Address: 0x40D191474B32E04b907698Ab4cA2a49221253918, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:39,225] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MIX/THE, Address: 0x4174d369DC35BaDE9dEC9d1B032E322517A945Ae, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:05:39,438] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-sfrxETH/FXS, Address: 0x425198EA58AB9CF9001f59C8AEB8c413A6dBe1b1, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:05:39,866] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ankrBNB/ankrETH, Address: 0x44d1F00E75fd074F6016bb1DC326DcCD5d04451B, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:05:44,882] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FIL/WBNB, Address: 0x45b4d277D73069f71a2d5c7390c56437AB0041CB, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:49,898] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/PLAY, Address: 0x45e175B4be980f1Dcf004e6584cEfD98E72F91c0, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:54,919] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/USDT OLD, Address: 0x46C69a989DC56747F007acfA4d6BC7c9FA8137bF, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:05:59,936] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/BUSD, Address: 0x483653bcF3a10d9a1c334CE16a19471a614F4385, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:04,950] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/TONCOIN, Address: 0x48821e0eD39e50AebEb1B079132B4C6604934F62, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:10,239] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-MAI/FRAX, Address: 0x49ad051F4263517BD7204f75123b7C11aF9Fd31C, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:15,440] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/WBNB, Address: 0x4Cd8a94975e275BD327431e2225f3afBA73B56d7, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:20,452] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ETH/WBNB, Address: 0x4d965b4AFF4e08F2DD99A4Ecaf1cb3a7f580Eb45, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:25,650] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-JRT/WBNB, Address: 0x4DbcF190cbdf69f3b013DA6FBB911943237ab913, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:30,666] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MIX/MATIC, Address: 0x4E2bEA8412D58c45f4C723df7223C3b21b9A309B, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:31,310] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDC/FRAX, Address: 0x512909b2bCeA4348Ea3284Bd167095deA10F2F40, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:06:31,469] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HBR/WBNB, Address: 0x5134729Cd5a5b40336BC3CA71349f2c108718428, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:06:36,485] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MPX/WBNB, Address: 0x51BfC6e47c96d2b8c564B0DdD2C44fC03707cdc7, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:41,501] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/FTM, Address: 0x535AEEab656c0fBb07DA64fe4AA3A15Dfc6834C8, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:46,518] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/FLOKI, Address: 0x537672472Bec1246eE9419e1716e221c9d0c04f6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:46,734] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MAI/BUSD, Address: 0x562a3d7E55D3F0E5859A30ab7c492787f0B6f52B, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:06:47,046] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/dXCAD, Address: 0x565F87C3D57bB990f138927f1E0cbb268A3E72dd, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:06:47,974] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/FEAR, Address: 0x573496B324b8AC077AA258CdE778C4b7F1AeC6af, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:06:52,987] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-IDIA/WBNB, Address: 0x57818b471AB3b7BDD558cFA0D5bc6Ab35534AAc7, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:58,175] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HBR/USDT, Address: 0x58C153d9dcaab03120Fd51ED6a4B7c38a6250Dd6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:06:58,683] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/FEAR, Address: 0x5980f099EE0584ff7F840a3672983bbF71E69a36, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:07:03,698] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-PLAY/THE, Address: 0x5A797d22b27c13a98Df8147aCf95771f7b43ac66, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:08,714] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HBR/USDT, Address: 0x5AF2ad763af72c0c4a58D528313A2537e2f9E32f, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:13,729] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT+/USD+, Address: 0x5cd928Aa2c1056254F8A4E22eAfE875175ffB976, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:17,998] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/SEF, Address: 0x5D5F0B239303024d28F9a75eBd634a9D12513725, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:07:20,757] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-WBNB/BUSD, Address: 0x6167c86326d3d088d6EBba415aAf172613BB579c, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:07:25,774] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/USDC, Address: 0x618f9Eb0E1a698409621f4F487B563529f003643, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:31,846] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FS/BUSD, Address: 0x6440889ed931cA08a0A06b064CB233138e8a263A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:32,334] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-IPAD/BUSD, Address: 0x678c521e10bAd0d451b16DdD23E5dF9E7B05A70E, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:07:37,532] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-WBNB/OATH, Address: 0x694C580E40C97fbab5A53400B6238DA5F81fdD5A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:42,544] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DUSD/FRAX, Address: 0x69cc21a73346e40608eF171Aa9b8D0E5795F82Df, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:47,563] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-wUSDR/USDC, Address: 0x6a3F976C3fD6E00b7840408EF771ed0be42d2A09, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:52,753] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ID/WBNB, Address: 0x6AdC40D6d4721e167BFc66F9517F4BDc721D5E15, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:07:58,029] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/dXCAD OLD, Address: 0x6c03177eb78EbDe271B24FD6E446b301db1AEdb1, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:03,232] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HAY/USDT, Address: 0x6ce8014488877f91234eF23012193De6bB0009a8, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:08,611] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DOLA/CUSD, Address: 0x7061F52ed4942021924745D454d722E52e057e03, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:13,628] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/multiBTC, Address: 0x706458510e841970F96061F43DAD4F654F06157f, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:13,904] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DAO/THE, Address: 0x71EADCb77a5B3B7749e08F52c595761D821C4638, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:08:19,385] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-LIBERA/THE, Address: 0x726caCbf72E650DcF8cA49d10BfA44CeeAdd4751, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:24,400] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FRAX/WBNB, Address: 0x735b028e646E28cA91F7882F0866426DEe4ff37D, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:29,416] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/wUSDR, Address: 0x743e019FB26EF4aB61339fBc07632Ebb175e28ca, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:29,607] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FRAX/sFRAX, Address: 0x7451ecbe4a56d103645E51A8d1d117606E8463b7, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:08:34,620] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/KOL, Address: 0x74A4f4722A4C105eCb9Be131A86d1e0344D4E6aA, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:39,632] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CHAM/THE, Address: 0x761327Ad8409Da88BD5485487b8f64B9A5295DD4, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:44,844] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ABOND/WBNB, Address: 0x7868245cAe5834b32B40CEE01f1b536AD75c7D09, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:49,860] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HBR/WBNB, Address: 0x78a5911620B1D1806869EcC1f0cEBDcB1Aa6932E, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:54,939] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/CUSD, Address: 0x793b5Ec33596CC5dCde59f909f87B558cCc9f392, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:08:59,957] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/GHNY, Address: 0x7B00238CDA460127E4d2CD6cE59155AaB2A5342D, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:04,974] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-AVAX/WBNB, Address: 0x7B2F91d226aD214Ac42ba21a597d99896311eCD1, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:09,993] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/THE OLD, Address: 0x7c7Ed76Dd95ffA7b899EE8Cc61aA8362d58aC420, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:15,008] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FEAR/BUSD, Address: 0x7d46E0498e485Ca5E5086E900F14A3fCC8A22ae0, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:20,025] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-LIBERA/WBNB, Address: 0x7d68e7B1aB7af2fD98827Bb4e2c652A2430141f8, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:25,041] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-SD/WBNB, Address: 0x7dceABfaceBd27f708FD9E6918c431d747D4Bf0E, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:30,059] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDC/BUSD, Address: 0x7e61c053527A7Af0c700aD9D2C8207E386273222, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:35,086] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ankrBNB/ANKR, Address: 0x7ef540f672Cd643B79D2488344944499F7518b1f, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:40,103] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/PRIMAL, Address: 0x7F17A57BB90D45Ca66C58dC9E562Fa93DE9d84A4, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:45,118] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USD+/THE, Address: 0x7F74D8C2A0D0997695eA121A2155e2710a6D62dc, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:50,133] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MAI/FRAX, Address: 0x7F7FfDC08d9A11DBB8F149FE16E3069540e7E012, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:55,432] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DJED/USDC, Address: 0x80551245C562380140668b7Df20a7e9c773d21Bd, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:09:55,749] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/BTCB, Address: 0x808247dBc5E63a309c13EDafE734Bf5b58034cb7, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:10:00,953] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-THE/FLOKI, Address: 0x82A72d1eeCb8fFFAbbD0073Db95D06bAC1577E09, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:05,970] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-GHNY/WBNB, Address: 0x833fDCd260811aF76AF0C2BD4eF7c961766C96f6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:10,985] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USD+/CUSD, Address: 0x84811aaBab26D15098f06ace9A97658ED93dDD3F, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:16,002] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-MORE/USDT, Address: 0x8540CF27FF440E2f53A13819c4788578658f6F83, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:21,018] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FRAX/CUSD, Address: 0x85D65c1cE99B2639985166C4A25d4c44EE1601bc, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:21,538] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/LQDR, Address: 0x89590BFDF3c5E052A27D5727fe1fD17d3026f41d, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:10:21,958] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ETH/frxETH, Address: 0x8A420aACA0c92e3f97CDcFdd852e01Ac5b609452, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:10:22,134] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HAY/ANKR, Address: 0x8bA94Ba4339Fb27309a573E97c6B7F30fAFcF00D, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:10:27,985] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/LISTA, Address: 0x8Df540ef17f44de603B6C044Baaf82994899068e, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:28,239] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ankrBNB/RDNT, Address: 0x8E5d38d9a303dc0f176E689C547A300365d2AB4B, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:10:28,628] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ETS Alpha/USD+, Address: 0x92573046BD4abA37d875eb45a0A1182ac63d5580, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:10:33,640] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-TAROT/BUSD, Address: 0x928FE97eEe1f921D80F25DC2EeA1dF280704fD03, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:38,938] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DAO/WBNB, Address: 0x948c553D8c25Ad7bD034086F0AaE9a9D3c028B90, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:43,954] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BNBx/SD, Address: 0x9698e0c7af13B6cEF8017A5c34eb2B3d053C491C, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:44,154] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/CHAM, Address: 0x972291C293a2eE6c7397017a6412035976E4326C, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:10:49,170] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DAO/BUSD, Address: 0x976583340036Aa93C5f0Bda9dA342e9EC6413A2e, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:54,185] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-eTHENA/WBNB, Address: 0x9798a3835c8C87bD92803C3A248aE0042FBE4c6c, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:10:59,202] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDV/USDT, Address: 0x97C4decba0438A4B6F871561963FC41B222dfa10, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:04,220] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/XCAD, Address: 0x97Ff96BAf308c910E3098b7B9D40B06759A3fABF, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:09,420] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/PLAY, Address: 0x9938256DD2C6A436233685E910EFaA44F6d8e81C, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:09,592] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/IPAD, Address: 0x9a5060C8D45a0Be40d2e0FC4C4Bd40B81b948F16, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:11:14,608] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ankrBNB/WBNB, Address: 0x9c9eAd6CFd1ED4Dd17Cd44eb12229364Dd541697, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:19,624] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/DEI, Address: 0x9d49bc4092C9FA2aA29B2AFC2723F9Ca97dC9374, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:24,808] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-BNBx/WBNB, Address: 0xA046644831b70aFdBfDAAB0bCf15a72D6c15d0eB, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:25,124] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/THE, Address: 0xA051eF9A6FBea340Bb734d022e7B6a3aD9fD9B06, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:11:25,555] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/HBR, Address: 0xA26D4fAC88227586e83312A4D2ddae42788f5c2f, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:11:31,256] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-GRAIN/WBNB, Address: 0xa6Da07730D7E9E5732E6483ceC67573e00ef45E7, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:36,273] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FRAX/BUSD, Address: 0xa91f86362E75c62512C6E790aB0784040f211179, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:41,485] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-wUSDR/USDC, Address: 0xA99c4051069B774102d6D215c6A9ba69BD616E6a, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:46,692] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ankrMATIC/MATIC, Address: 0xAcc047c2D898BD36bA24d34Fe197d4AbC82C7E3c, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:51,971] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/USDC-jCHF-120-vLP, Address: 0xADbE21683F4C7a8f0Ba8dCaD54e49085352a51AF, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:11:52,162] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ETH/BTCB, Address: 0xAF510a3f6888C64A976d5AA1AE42113bB135a19a, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:11:52,355] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/OATH, Address: 0xAF6389e0281337cf810b5843EBaE12dbF5A0eAf4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:11:57,530] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-fBOMB/CGPT, Address: 0xb072badF1c7c0d679eD204bBAE50d9C2F7c6F87F, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:02,546] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ETS Alpha/BUSD, Address: 0xb23a34cc853E47D8bfd148Baf066B6F1541571c9, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:07,562] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-TAROT/WBNB, Address: 0xB2604B72b3Aa4aF8d0419c736de2D261b40ec755, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:13,289] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-WBNB/BIFI, Address: 0xB8C1557ddfc61C6c48a7d12F11cC1F8CF3b4d4E6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:18,305] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-jBRL/BRZ, Address: 0xB95c58277DdE24801C2A460BceA25a2d28A1591B, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:23,320] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DAO/WBNB, Address: 0xB96e4f3816DAea60EC84865623892671a4839F2A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:28,336] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HAY/THE, Address: 0xb985E2cB89849975d96e260c792073d7b151033d, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:33,546] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DAI/USDT, Address: 0xbabEF76f5fA36a37236E0467beE30BacBC371AA6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:38,560] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/BIFI, Address: 0xbaD27C20d0A2428251585f1FD509685e48f307bD, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:39,065] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BNBx/THE, Address: 0xBB25DD702471aDb5d40df0f382586Cb5CBf49Bd2, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:12:44,082] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/BUSD, Address: 0xbb6CD6EfFB4861971Af675ca5fb8964873bdab2d, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:49,100] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HAY/USDT+, Address: 0xBc1Aa784F7FfA59c1B2098c1005dd0FAD2F7E46E, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:12:49,484] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-wUSDR/DOLA, Address: 0xbCE9518273991717C04e757a16D4AF60CdA8171d, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:12:49,649] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-HAY/USD+, Address: 0xbE284ed0e5623608446f769EA81C9F9968c3D3FF, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:12:55,055] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-WBNB/MATIC, Address: 0xBf8a33070C3a58aeB7f2AB0729A84B6322eb1aCE, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:00,070] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDC/USD+, Address: 0xbF9dC59A2370f1E11Dc34c889C69d56BD7786db6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:05,091] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/NFTB, Address: 0xC03D86b6685Aec46909eA5c54943e2a1238E02Ac, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:10,107] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDC/DEI, Address: 0xC092c8ef0909E422A9B7733734d971215F52fC2D, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:15,123] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-liveThe/THE, Address: 0xc1c87706CBd554F4e936579d277E337Ea84461bA, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:20,140] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-sfrxETH/frxETH, Address: 0xc2D245919dB52eA4D5d269b0C710056639176eaD, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:20,375] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-OATH/BUSD, Address: 0xc2dc97A4afE061186Ad5Ca5231f964a97Ce305eb, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:13:20,578] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HBR/THE, Address: 0xC3a5da0C2BAC365988d88220A7e0fF8AB64BD4A4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:13:20,762] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ankrBNB/DUSD, Address: 0xC47dF29C6454C2206e54657f4716eC91558bc67c, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:13:21,112] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-TWT/WBNB, Address: 0xC4A17162da872640c49cC191759F8B423539c7Ea, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:13:21,289] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/WBNB, Address: 0xC53fe45E0047965da638aa70E9B6be3d68E2f80f, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:13:26,304] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-IPAD/BUSD, Address: 0xc54f536FF19FFcE40A82cCa2903B1D7D48Af69e4, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:31,319] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DOLA/WBNB, Address: 0xc5856601712E8a74d57cdc7a47fB1B41C1a6Fae2, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:36,532] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-PRIMAL/BUSD, Address: 0xC6B5289f0Db1738f8C1D26cC09942028527bdDA3, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:37,111] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/WBNB, Address: 0xc7419EBbc4b259C50D7Eeaba49940688A5d52Afa, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:13:42,573] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XRP/WBNB, Address: 0xC9688a1e9dBE45F253CC77cB9726A11b323bFD54, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:47,590] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FITFI/BUSD, Address: 0xcAe2C0d6937671490D3bcE4C21d57fF313f407Eb, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:52,606] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-fBOMB/WBNB, Address: 0xCcDEdaC1973b6d2542fB1b7EcE843b81A9ee7070, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:13:57,636] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CSIX/USDT, Address: 0xCE7C38ECe02b55070208b2e070585eA5321748e1, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:02,652] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-qTHE/THE, Address: 0xCEd2490a69aeD204e7A10e4Aa10DdDce5224287D, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:03,017] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BTCB/WBNB, Address: 0xD328D129E46f9B978416599913102e8CD64593F3, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:14:08,610] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-FRAX/FXS, Address: 0xd6C883ABA697b33110e42077D28361aa3E48f26A, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:13,627] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-UNW/THE, Address: 0xd714206a7D63F5a2d613064815995E9CC7061988, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:18,642] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-NGL/USDT, Address: 0xD949476184B9c94Ed2130E8175D4139654CE2339, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:19,115] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-BNBx/ETH, Address: 0xd9BC6271abBE5dd01731B1b9aC2C1Cb0ea5Be246, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:14:24,130] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-XCAD/BTCB OLD, Address: 0xd9F7096625B65Ac37c09d05c1c4548edfcCe9fBE, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:29,146] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FITFI/WBNB, Address: 0xd9f88F54a73B37463fb8F15ece98e0D1DcdCAAB6, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:34,162] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/THE, Address: 0xDA2E32203EEe658e0E9b9E1b766ac1ceDb88d1f1, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:39,177] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/RDNT, Address: 0xda57e73e5A2fA00C5c6B660454c1950DCB03E958, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:44,461] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/THE, Address: 0xdAaC487bB3a411cB9251794bb7c7B04cb6d1aB26, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:49,774] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-PION/WBNB, Address: 0xDC1e387fC2697F3737EE197712BfeF9e1101ccd5, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:54,970] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/THE, Address: 0xdC81698F98e275785741F96961f246368FDd5866, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:14:59,986] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DUSD/WBNB, Address: 0xdd0118F593c91ef5FA40C34d5687654C215C3D98, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:05,187] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MULTI/BUSD, Address: 0xdE4Cc4446205d1138EcAa48B2CB22b8e06E69BD4, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:10,204] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/PRIMAL, Address: 0xde72DD50Dd0ca9C8c48b04F74c5246B5545969D0, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:15,409] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-CHAM/BUSD, Address: 0xDf63A43aEFb5c1Aa4040a3a121d2a8C00EeBE7d8, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:15,588] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-DAI/MAI, Address: 0xe03e9EcC7d4C45c6985bfB909D9Bb3ACa5Ef18c0, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:15:20,605] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-XCAD/BUSD OLD, Address: 0xe200B5B3F08d1254d05d8797FFA1f99730C0025c, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:25,877] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-ETH/XCAD OLD, Address: 0xe2d25A87e97a1016c35F736Ea77A4d6Bd1919E74, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:31,059] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-MAI/BUSD, Address: 0xe459556595A224D7F12b45E93138F4A1265AC618, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:36,333] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/USD+, Address: 0xE4B5493e357859FB73bE73b29B1034cF63547986, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:41,528] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USD+/BUSD, Address: 0xe6eAb9B5B0A27866f30091DC76AFE1Ffe70a8507, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:46,841] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDC/MIX, Address: 0xE9993F367d6C37d4EE853344731FDd1012bAF272, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:51,857] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-LVL/WBNB, Address: 0xea3f8926fA9Ead0B4B05569AD21FD1DCEA06b1D4, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:15:56,872] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/USD+, Address: 0xea9abc7AD420bDA7dD42FEa3C4ACd058902A5845, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:01,891] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-MATIC/BUSD, Address: 0xEB58A4D07990fF50b9F8289701cBdDf9052570B5, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:06,915] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-IDIA/C98, Address: 0xeB6E35fe9f507eb1A35fb048584823652D4D2797, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:12,281] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/LQDR, Address: 0xEC4484c7F7671914E897b1AEb8418Fe12E320f21, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:17,298] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FS/USDC, Address: 0xeD6A13A30760C3a3795C5F5d7b6F911a3de0edD9, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:22,312] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDC/MIX, Address: 0xeEbdB610Ef49aD004344Bb18cC3cFD3552040589, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:27,501] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-USDT/WBNB, Address: 0xF048CF3EAc3c17aD47ae1C4e37408040177a8554, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:32,771] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-HAY/WBNB, Address: 0xF0e87ccE713110763B1D68A6EAFaf3046D1F59e3, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:38,132] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-OATH/LQDR, Address: 0xF2e2ADb0bec256184cF72DdF1642CEE7A6706866, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:43,149] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-C98/CUSD, Address: 0xF4d3aFa871f1Bb9d5Db7f057eD555a4c549b5174, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:43,568] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-USDT/FS, Address: 0xf68C4Ff2eed4E47B683b38aA74D7AD05AD3a303F, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:16:48,589] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FTM/WBNB, Address: 0xf753B7E59e1c010B5FD89737E874D4CA51D9cc23, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:53,606] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-DAO/BUSD, Address: 0xF81b6B8aAaD4c37F6F2E8Aa9988f28ea8E82Bb49, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:16:53,772] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-WBNB/rBNB, Address: 0xf9Cf0b2fF50D13ABa7aaD7e9314b096bfC0ACE7c, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:16:54,020] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: sAMM-ankrBNB/WBNB, Address: 0xfa0429A7EAb25EC8D31e247E725Afd931Cf6bdFe, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:16:59,413] 	ERROR 	66 	pair_data.py 	<module>() 	Error occurred during Pair Data process. Pair: vAMM-FIL/USDT, Address: 0xfF755d0C1C5b9051a3617221e10394742679F5a1, Error: HTTPSConnectionPool(host='api.studio.thegraph.com', port=443): Read timed out. (read timeout=5)
[2024-08-02 01:17:10,283] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-02 01:17:10,283] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-02 01:17:10,742] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:11,252] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:11,469] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:11,651] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:11,872] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:13,231] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:13,768] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:14,721] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:15,884] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:17,067] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:17,241] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:20,444] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:21,558] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:21,809] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:22,662] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:23,119] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:23,508] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:25,996] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aDAO-ankrBNB, Address: 0x11C92deD470A50C96d2e5EFfEdc890cd4bd2502e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:26,684] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:28,474] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:29,583] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:34,045] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:35,803] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 01:17:43,232] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-02 01:17:43,232] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-02 01:18:15,829] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-02 01:18:16,701] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-02 01:53:48,277] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-02 01:53:48,890] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-02 01:54:00,054] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-02 01:54:00,634] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-02 01:54:09,186] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-02 01:54:09,769] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-02 01:55:10,627] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/LISTA, Address: 0x8df540ef17f44de603b6c044baaf82994899068e, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:56:10,788] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: MORE/arcUSD, Address: 0x3bfc63eb779811f59d41045394f612da3f450678, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:57:10,945] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: qTHE/THE, Address: 0x0d075baccb0614ee93ebe761a9803d7ded662ffa, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:57:12,211] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/ANKR, Address: 0xe934278276c0274aac95dadb9783f02a27c351ff, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:58:12,365] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: DAI/USDT, Address: 0xbabef76f5fa36a37236e0467bee30bacbc371aa6, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 01:59:12,835] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: stkBNB/THE, Address: 0x2afed1ca1bc414e123b1c4e30e8f6fc513c8ee72, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:00:13,097] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDC/PLAY, Address: 0x16184ec3a17285b33c22b6252c2d94ca54d03341, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:01:13,532] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDT/FLOKI, Address: 0x537672472bec1246ee9419e1716e221c9d0c04f6, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:02:14,345] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/rBNB, Address: 0xf9cf0b2ff50d13aba7aad7e9314b096bfc0ace7c, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:03:14,695] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: OOE/BUSD, Address: 0x15538fc89447927cfef14ff2e5f7d870fee98330, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:04:16,277] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: MAI/FXS, Address: 0x10f9f7355fb75c73718afad8adbc7bf72c5a0715, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:05:16,579] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ETH/PLAY, Address: 0x9938256dd2c6a436233685e910efaa44f6d8e81c, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:06:16,827] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/MATIC, Address: 0xe47cf3aeff7a07dbefef391339cad4988b162ea0, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:07:17,565] 	ERROR 	93 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: MULTI/BUSD, Address: 0xde4cc4446205d1138ecaa48b2cb22b8e06e69bd4, Error: Expecting value: line 1 column 1 (char 0)
[2024-08-02 02:11:00,799] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-02 02:11:00,799] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-02 02:12:10,572] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-02 02:12:10,572] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-02 02:12:24,155] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-02 06:19:38,444] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-02 06:23:15,185] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-02 06:23:16,174] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-02 06:23:18,199] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-02 06:23:18,199] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-02 06:23:19,771] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-02 06:23:19,771] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-02 06:23:22,686] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-02 06:23:23,510] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-02 06:24:52,525] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-02 06:24:52,525] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-02 06:24:52,674] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:52,906] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:53,039] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:53,160] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:53,261] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:53,927] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:54,166] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:54,689] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:55,313] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:55,901] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:56,011] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:57,622] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:58,190] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:58,296] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:58,745] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:58,967] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:24:59,213] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:25:00,899] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:25:01,889] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:25:02,478] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:25:04,890] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:25:05,821] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 06:25:11,972] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-02 06:25:11,973] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-02 06:25:35,113] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-02 06:25:35,973] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-02 06:49:27,324] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-02 06:49:27,950] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-02 06:49:41,744] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-02 06:49:42,336] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-02 06:49:52,447] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-02 06:49:53,035] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-02 06:52:33,180] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-02 06:52:33,180] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-02 06:53:09,483] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-02 06:53:09,483] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-02 06:53:18,645] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-02 12:23:50,511] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-02 12:27:48,610] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-02 12:27:49,306] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-02 12:27:56,247] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-02 12:27:56,247] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-02 12:27:58,597] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-02 12:27:58,597] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-02 12:28:00,879] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-02 12:28:01,700] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-02 12:29:14,382] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-02 12:29:14,382] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-02 12:29:14,549] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:14,857] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:15,002] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:15,126] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:15,241] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:16,064] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:16,330] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:16,909] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:17,638] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:18,312] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:18,516] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:20,512] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:21,191] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:21,317] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:21,832] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:22,106] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:22,415] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:24,602] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:25,723] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:26,364] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:29,247] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:30,603] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 12:29:36,570] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-02 12:29:36,570] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-02 12:30:05,147] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-02 12:30:06,005] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-02 12:58:28,100] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-02 12:58:28,701] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-02 12:58:49,671] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-02 12:58:50,251] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-02 12:58:59,488] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-02 12:59:00,071] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-02 13:01:01,210] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-02 13:01:01,210] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-02 13:01:46,186] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-02 13:01:46,186] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-02 13:02:00,121] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-02 18:17:35,529] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-02 18:18:06,668] 	ERROR 	122 	id_data_v2.py 	<module>() 	Error occurred during ID Data process. Error: {'code': -32073, 'message': 'Failed to rebuild response'}
[2024-08-02 18:18:07,367] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-02 18:18:08,884] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-02 18:18:08,884] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-02 18:18:10,848] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-02 18:18:10,849] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-02 18:18:13,809] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-02 18:18:14,611] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-02 18:20:02,474] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-02 18:20:02,474] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-02 18:20:02,681] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:03,008] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:03,187] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:03,347] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:03,505] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:04,443] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:04,756] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:05,398] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:06,202] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:06,945] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:07,128] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:09,457] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:10,202] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:10,386] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:10,988] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRXETH-STKBNB, Address: 0xde0559d2720436978d8cEdc0144Ceba075BbfA1D, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:11,303] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:11,582] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:13,734] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:14,949] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:15,657] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:18,795] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:19,971] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-02 18:20:27,861] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-02 18:20:27,861] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-02 18:21:00,757] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-02 18:21:01,653] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-02 18:39:22,258] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-02 18:39:22,872] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-02 18:39:59,923] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-02 18:40:00,507] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-02 18:40:13,670] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-02 18:40:14,263] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-02 18:43:25,759] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-02 18:43:25,759] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-02 18:44:20,355] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-02 18:44:20,355] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-02 18:44:31,555] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-08-03 00:58:11,070] 	INFO 	23 	id_data_v2.py 	<module>() 	ID Data Started
[2024-08-03 01:04:07,296] 	INFO 	120 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-08-03 01:04:08,027] 	INFO 	26 	day_data.py 	<module>() 	Day Data Started
[2024-08-03 01:04:09,302] 	INFO 	72 	day_data.py 	<module>() 	Day Data Ended
[2024-08-03 01:04:09,302] 	INFO 	78 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-08-03 01:04:12,157] 	INFO 	130 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-08-03 01:04:12,157] 	INFO 	137 	day_data.py 	<module>() 	Day Data Combined Started
[2024-08-03 01:04:15,330] 	INFO 	167 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-08-03 01:04:16,151] 	INFO 	37 	pair_data.py 	<module>() 	Pair Data Started
[2024-08-03 01:05:33,254] 	INFO 	111 	pair_data.py 	<module>() 	Pair Data Ended
[2024-08-03 01:05:33,254] 	INFO 	128 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-08-03 01:05:33,411] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:33,913] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:34,045] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-BUSD, Address: 0x0Cd7F0d5478FEFe59F2B9F5aBa623706f2924e77, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:34,204] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:35,087] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:35,402] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:35,676] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-EDU, Address: 0x4bD39cfb05545c4238316dA69eCadA1b4CaABC05, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:35,941] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:36,723] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:37,468] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:39,790] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:40,506] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:40,642] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:41,630] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:41,920] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:46,358] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:47,584] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:48,241] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aANKRBNB-USDT, Address: 0xc1716bEa36140Fa08476742d80cb28CEcD492A6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:51,191] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:52,266] 	ERROR 	167 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 2862, Address: 0xA547a2E5D256b08644425029Fec0aCdb634388F7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-08-03 01:05:59,855] 	INFO 	203 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-08-03 01:05:59,855] 	INFO 	210 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-08-03 01:06:25,220] 	INFO 	240 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-08-03 01:06:26,089] 	INFO 	39 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-08-03 01:35:44,108] 	INFO 	154 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-08-03 01:35:44,725] 	INFO 	24 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-08-03 01:36:09,209] 	INFO 	72 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-08-03 01:36:09,796] 	INFO 	24 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-08-03 01:36:21,432] 	INFO 	86 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-08-03 01:36:22,017] 	INFO 	36 	tvl_data.py 	<module>() 	TVL Data Started
[2024-08-03 01:38:26,675] 	INFO 	97 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-08-03 01:38:26,676] 	INFO 	112 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-08-03 01:39:12,201] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-08-03 01:39:12,201] 	INFO 	189 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-08-03 01:39:30,172] 	INFO 	233 	tvl_data.py 	<module>() 	TVL Data Combined Ended
