[2024-09-01 01:05:52,080] 	INFO 	14 	id_data_v2.py 	<module>() 	ID Data Started
[2024-09-01 01:09:56,002] 	INFO 	163 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-09-01 01:09:56,758] 	INFO 	14 	id_data_v3.py 	<module>() 	ID Data Started
[2024-09-01 01:09:57,611] 	INFO 	40 	id_data_v3.py 	<module>() 	ID Data Ended
[2024-09-01 01:09:58,358] 	INFO 	18 	day_data.py 	<module>() 	Day Data Started
[2024-09-01 01:10:02,653] 	INFO 	64 	day_data.py 	<module>() 	Day Data Ended
[2024-09-01 01:10:02,654] 	INFO 	70 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-09-01 01:10:04,342] 	INFO 	123 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-09-01 01:10:04,342] 	INFO 	130 	day_data.py 	<module>() 	Day Data Combined Started
[2024-09-01 01:10:08,273] 	INFO 	160 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-09-01 01:10:09,093] 	INFO 	30 	pair_data.py 	<module>() 	Pair Data Started
[2024-09-01 01:11:02,827] 	INFO 	104 	pair_data.py 	<module>() 	Pair Data Ended
[2024-09-01 01:11:02,827] 	INFO 	121 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-09-01 01:11:03,171] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:03,615] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:03,820] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:04,278] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:04,482] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-DOLA, Address: 0xdB6BfF81311C5C4F72668D9C4c8a5E2CB4584A82, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:05,347] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-STKBNB, Address: 0x84b78452A97C5afDa1400943333F691448069A29, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:05,583] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:06,048] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:06,967] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:07,400] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-USDV, Address: 0x739e561786C920D025d57eD99be5D4EcA3458E3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:08,317] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:08,763] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-OOE, Address: 0x3401Cf94c6F81347b426Df1D0f6269b7A24fEb2E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:09,393] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:09,620] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:09,835] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-BTE, Address: 0x9D49003383aB126C563ae2B7d545DB003e657F53, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:10,061] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDC-WUSDR, Address: 0xcbdE6C4f202eCc13267fD53913bc44B4Dd6eF998, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:10,728] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSolvBTC-BTCB, Address: 0x575A951aD021d4297ac125Be88eE4620652D5C12, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:11,639] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSFRXETH-FRXETH, Address: 0xd9e98A73102391b3D7d1D94C0c58541aBf99a14F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:11,855] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aPNP-WBNB, Address: 0x187784bC6812b056f4a54d84CDC98075F2d2eec6, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:12,101] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aORBS-WBNB, Address: 0x130348553b3dEA5d65767Dc390eFF257F9a9181d, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:12,330] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aOATH-ERN, Address: 0xDF5751BBEf0241878852253F8541A02c3Cbc2dd1, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:12,991] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:13,214] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aID-WBNB, Address: 0xB66566fD115CAf17633504A5165a319F17D9F096, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:14,142] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:14,357] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:15,466] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:16,117] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:17,064] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:17,967] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aEQB-WBNB, Address: 0x89217690eb025Ef16124316f4A7884c13b30fb6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:18,170] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aEQB-FRXETH, Address: 0xe6385768234224CF79d84c390E346d43bC812824, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:19,467] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:21,011] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ETH, Address: 0x6B32E9178a6670dc9b19a74FE5080C54ea5347C7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:21,231] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:21,921] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aARKEN-WBNB, Address: 0xCB995DaE5238c1e08C7289b335c80ED8d129A46b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:24,332] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-8-THE a082, Address: 0x8929E532E551c82f5736aa18C78440691BC542D9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:26,723] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:26,925] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-11-THE 2ff5, Address: 0xe1Ad12B9f713710a8FFF593eB1c6E5F82d3C0b3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:27,142] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare a373, Address: 0xaB6f06A33f38cBa5A5312DE24151CB91dA2b0Eb0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:28,470] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 31eD, Address: 0x37CbdBb97C34ba577ADbFbB80b517cD6caB636E8, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 01:11:35,163] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-09-01 01:11:35,163] 	INFO 	204 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-09-01 01:12:03,979] 	INFO 	247 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-09-01 01:12:04,875] 	INFO 	30 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-09-01 01:21:49,720] 	INFO 	133 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-09-01 01:21:50,614] 	INFO 	31 	fee_data.py 	<module>() 	Fee Data Started
[2024-09-01 01:30:18,518] 	INFO 	132 	fee_data.py 	<module>() 	Fee Data Ended
[2024-09-01 01:30:19,185] 	INFO 	16 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-09-01 01:30:32,127] 	INFO 	77 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-09-01 01:30:32,758] 	INFO 	15 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-09-01 01:30:43,463] 	INFO 	79 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-09-01 01:30:44,088] 	INFO 	28 	tvl_data.py 	<module>() 	TVL Data Started
[2024-09-01 01:32:18,838] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/BUSD, Address: 0x483653bcf3a10d9a1c334ce16a19471a614f4385, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:19,027] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ETH/BNB, Address: 0x1d168c5b5dea1c6da0e9fd9bf4b7607e4e9d8eec, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:19,202] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BUSD/THE, Address: 0x34b897289fccb43c048b2cea6405e840a129e021, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:19,360] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BTCB/BNB, Address: 0xd328d129e46f9b978416599913102e8cd64593f3, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:19,538] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/THE, Address: 0x63db6ba9e512186c2faadacef342fb4a40dc577c, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:19,707] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: DEI/BUSD, Address: 0x06589abd54582783142e3d1165722e7e10483de0, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:19,872] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: IDIA/BUSD, Address: 0x3c552e8ac4473222e3d794adecfa432eace85929, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:20,036] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/DEUS, Address: 0xc8da40f8a354530f04ce2dde98ebc2960a9ea449, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:20,199] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDT/BNB, Address: 0x6be6a437a1172e6c220246ecb3a92a45af9f0cbc, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:20,369] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: lisUSD/BUSD, Address: 0x93b32a8dfe10e9196403dd111974e325219aec24, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:20,582] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/stkBNB, Address: 0x2b3510f57365aa17bff8e6360ea67c136175dc6d, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:20,751] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: FITFI/BUSD, Address: 0xcae2c0d6937671490d3bce4c21d57ff313f407eb, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:20,914] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: FRAX/BUSD, Address: 0x7fcfe6b06c1f6aad14884ba24a7f315c1c0c2cef, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:21,091] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: GHNY/BNB, Address: 0xa97e46dc17e2b678e5f049a2670fae000b57f05e, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:21,272] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: TAROT(old)/BNB, Address: 0xb2604b72b3aa4af8d0419c736de2d261b40ec755, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 01:32:21,272] 	INFO 	89 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-09-01 01:32:21,272] 	INFO 	104 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-09-01 01:33:30,153] 	INFO 	175 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-09-01 01:33:30,153] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-09-01 01:33:49,099] 	INFO 	226 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-09-01 01:33:49,907] 	INFO 	26 	fee_tvl_data.py 	<module>() 	Fee TVL Data Started
[2024-09-01 01:33:55,289] 	INFO 	62 	fee_tvl_data.py 	<module>() 	Fee TVL Data Ended
[2024-09-01 02:49:16,477] 	INFO 	14 	id_data_v2.py 	<module>() 	ID Data Started
[2024-09-01 02:55:24,127] 	INFO 	163 	id_data_v2.py 	<module>() 	ID Data Ended
[2024-09-01 02:55:24,942] 	INFO 	14 	id_data_v3.py 	<module>() 	ID Data Started
[2024-09-01 02:55:25,681] 	INFO 	40 	id_data_v3.py 	<module>() 	ID Data Ended
[2024-09-01 02:55:26,635] 	INFO 	18 	day_data.py 	<module>() 	Day Data Started
[2024-09-01 02:55:28,285] 	INFO 	64 	day_data.py 	<module>() 	Day Data Ended
[2024-09-01 02:55:28,285] 	INFO 	70 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-09-01 02:55:29,679] 	INFO 	123 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-09-01 02:55:29,679] 	INFO 	130 	day_data.py 	<module>() 	Day Data Combined Started
[2024-09-01 02:55:33,284] 	INFO 	160 	day_data.py 	<module>() 	Day Data Combined Ended
[2024-09-01 02:55:34,158] 	INFO 	30 	pair_data.py 	<module>() 	Pair Data Started
[2024-09-01 02:56:17,435] 	INFO 	104 	pair_data.py 	<module>() 	Pair Data Ended
[2024-09-01 02:56:17,435] 	INFO 	121 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-09-01 02:56:17,562] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: astERN-ERN, Address: 0xcB2B3d8239759b4ad1dFe6392Bc39DEe4F23303B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:17,756] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aankrBNB-DUSD, Address: 0xf96269E2af44e45f53cE8BBa9a280E3db7e54d62, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:17,869] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aXCAD-WBNB, Address: 0xe2624920C88b470B78EFAdfdE51Dd0E2C841934B, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:18,085] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-USDC, Address: 0x3f8062cf591a918Bc3B183fa241ec49efBd30e2b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:18,192] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWUSDR-DOLA, Address: 0xdB6BfF81311C5C4F72668D9C4c8a5E2CB4584A82, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:18,623] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-STKBNB, Address: 0x84b78452A97C5afDa1400943333F691448069A29, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:18,740] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-RBNB, Address: 0x3cAd1CBA60f695Ec7FA522Ec486f55D77C270b18, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:18,940] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-LQDR, Address: 0x19934Ce0f772EC67873Bbd1127f173e6c79856a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:19,403] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aWBNB-BIFI, Address: 0xCC0b8D28e7c31555a3889CDc05AF55bfF57c368A, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:19,590] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-USDV, Address: 0x739e561786C920D025d57eD99be5D4EcA3458E3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:20,057] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-PLAY, Address: 0xa7aBA8136C5758B47312233C684547B651FCF775, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:20,277] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-OOE, Address: 0x3401Cf94c6F81347b426Df1D0f6269b7A24fEb2E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:20,633] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-ERN, Address: 0x8DCDF3CbD3a588a2e2FB607BdC9180e4FefA583b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:20,737] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-DUSD, Address: 0xCf4cf048d0c754A71d559296aC1ccc9aeb0b25Be, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:20,832] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDT-BTE, Address: 0x9D49003383aB126C563ae2B7d545DB003e657F53, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:20,930] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aUSDC-WUSDR, Address: 0xcbdE6C4f202eCc13267fD53913bc44B4Dd6eF998, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:21,388] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSolvBTC-BTCB, Address: 0x575A951aD021d4297ac125Be88eE4620652D5C12, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:21,888] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aSFRXETH-FRXETH, Address: 0xd9e98A73102391b3D7d1D94C0c58541aBf99a14F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:21,981] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aPNP-WBNB, Address: 0x187784bC6812b056f4a54d84CDC98075F2d2eec6, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:22,072] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aORBS-WBNB, Address: 0x130348553b3dEA5d65767Dc390eFF257F9a9181d, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:22,156] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aOATH-ERN, Address: 0xDF5751BBEf0241878852253F8541A02c3Cbc2dd1, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:22,523] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aJBRL-USDC, Address: 0xd63bBA6078a328b93758Cc7556e21D3380397D41, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:22,674] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aID-WBNB, Address: 0xB66566fD115CAf17633504A5165a319F17D9F096, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:23,311] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aHAY-FRAX, Address: 0x30F8542ede13c68c5B4ed2922401c8BA63d88e59, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:23,412] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aGRAIN-WBNB, Address: 0x1f060bE9D1D3Bd3ACC5392aC066C6B437780ABe0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:23,954] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aFRAX-ERN, Address: 0x1C2D4F310aeA872C5BD55790D2D78Ca7B31992a3, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:24,222] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-inETH, Address: 0x52e3e02B5961292C388A1faE1ce4EaD724D4E806, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:24,659] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aETH-STKBNB, Address: 0x8b41d72def3867E19f2285B45DA655e24928018F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:25,105] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aEQB-WBNB, Address: 0x89217690eb025Ef16124316f4A7884c13b30fb6F, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:25,206] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aEQB-FRXETH, Address: 0xe6385768234224CF79d84c390E346d43bC812824, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:25,972] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aCASH-USDT, Address: 0x45F1Fdb00fB78174196Fa109A27Cdbd07f67F85e, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:26,743] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ETH, Address: 0x6B32E9178a6670dc9b19a74FE5080C54ea5347C7, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:26,838] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aBNBX-ERN, Address: 0xc7426Dce489E6b2d580Fd480Ef72D57e5d7643f5, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:27,121] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: aARKEN-WBNB, Address: 0xCB995DaE5238c1e08C7289b335c80ED8d129A46b, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:28,452] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-8-THE a082, Address: 0x8929E532E551c82f5736aa18C78440691BC542D9, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:29,857] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-14-THE B802, Address: 0x8b8a362116f5F632B81e85e347846590bB4Be2A4, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:29,944] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: IV-11-THE 2ff5, Address: 0xe1Ad12B9f713710a8FFF593eB1c6E5F82d3C0b3E, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:30,031] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare a373, Address: 0xaB6f06A33f38cBa5A5312DE24151CB91dA2b0Eb0, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:30,666] 	ERROR 	161 	pair_data.py 	<module>() 	Error occurred during Pair Data Fusion process. Pair: DEShare 31eD, Address: 0x37CbdBb97C34ba577ADbFbB80b517cD6caB636E8, Error: "None of [Index(['id', 'date', 'tvlUSD', 'volumeUSD', 'volumeToken0', 'volumeToken1',\n       'token0Price', 'token1Price', 'feesUSD', '__typename'],\n      dtype='object')] are in the [columns]"
[2024-09-01 02:56:36,425] 	INFO 	197 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-09-01 02:56:36,425] 	INFO 	204 	pair_data.py 	<module>() 	Pair Data Combined Started
[2024-09-01 02:57:02,192] 	INFO 	247 	pair_data.py 	<module>() 	Pair Data Combined Ended
[2024-09-01 02:57:03,159] 	INFO 	30 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-09-01 03:10:22,565] 	INFO 	133 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-09-01 03:10:23,437] 	INFO 	31 	fee_data.py 	<module>() 	Fee Data Started
[2024-09-01 03:23:19,189] 	INFO 	132 	fee_data.py 	<module>() 	Fee Data Ended
[2024-09-01 03:23:19,798] 	INFO 	16 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-09-01 03:23:32,882] 	INFO 	77 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-09-01 03:23:33,467] 	INFO 	15 	revenue_data_v2.py 	<module>() 	Revenue Data Started
[2024-09-01 03:23:42,853] 	INFO 	79 	revenue_data_v2.py 	<module>() 	Revenue Data Ended
[2024-09-01 03:23:43,438] 	INFO 	28 	tvl_data.py 	<module>() 	TVL Data Started
[2024-09-01 03:25:24,832] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ETH/BTCB, Address: 0x1ebdf6e38ae6461ef5c8e97346a02934ba6fad84, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:24,954] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ETH/LIQ, Address: 0xdf26702b1a510bc6860b2a1df11219f216b91445, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:25,089] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: DUSD/BNB, Address: 0xdd0118f593c91ef5fa40c34d5687654c215c3d98, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:25,222] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/RDNT, Address: 0xda57e73e5a2fa00c5c6b660454c1950dcb03e958, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:25,355] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: FRAX/sFRAX, Address: 0x7451ecbe4a56d103645e51a8d1d117606e8463b7, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:25,528] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDT/SEF, Address: 0x5d5f0b239303024d28f9a75ebd634a9d12513725, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:25,672] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: FRAX/BNB, Address: 0x735b028e646e28ca91f7882f0866426dee4ff37d, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:25,968] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: fBOMB/CGPT, Address: 0xb072badf1c7c0d679ed204bbae50d9c2f7c6f87f, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:26,105] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ETH/HBR, Address: 0xa26d4fac88227586e83312a4d2ddae42788f5c2f, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:26,237] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDC/BUSD, Address: 0x7e61c053527a7af0c700ad9d2c8207e386273222, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:26,378] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: USDT/BUSD, Address: 0x6321b57b6fdc14924be480c54e93294617e672ab, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:26,521] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ETH/CHAM, Address: 0x972291c293a2ee6c7397017a6412035976e4326c, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:26,656] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: BNB/BUSD, Address: 0x483653bcf3a10d9a1c334ce16a19471a614f4385, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:26,794] 	ERROR 	85 	tvl_data.py 	<module>() 	Error occurred during TVL Data process. Pair: ETH/BNB, Address: 0x1d168c5b5dea1c6da0e9fd9bf4b7607e4e9d8eec, Error: Expecting value: line 1 column 1 (char 0)
[2024-09-01 03:25:31,127] 	INFO 	89 	tvl_data.py 	<module>() 	TVL Data Ended
[2024-09-01 03:25:31,127] 	INFO 	104 	tvl_data.py 	<module>() 	TVL Data Fusion Started
[2024-09-01 03:26:03,300] 	INFO 	175 	tvl_data.py 	<module>() 	TVL Data Fusion Ended
[2024-09-01 03:26:03,300] 	INFO 	182 	tvl_data.py 	<module>() 	TVL Data Combined Started
[2024-09-01 03:26:15,502] 	INFO 	226 	tvl_data.py 	<module>() 	TVL Data Combined Ended
[2024-09-01 03:26:16,109] 	INFO 	26 	fee_tvl_data.py 	<module>() 	Fee TVL Data Started
[2024-09-01 03:26:21,340] 	INFO 	62 	fee_tvl_data.py 	<module>() 	Fee TVL Data Ended
